version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=ms-spring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
